### ISSUE TITLE
add support for initiatives in selection panel

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#116]
A full accounting of why this is needed is here:
https://trello.com/c/NalZvwXm/24-project-initiatives-for-revenue-reporting

@jugglinmike do you have the bandwidth to add another select box for this? I haven't landed support for initiative tracking in the API but I will do so tomorrow.

No worries if you can't, I just need to know whether I should plan to do this myself or not.

/ref bocoup/admiralty#880

**Comment by jugglinmike** [comment]
I do not currently have the time necessary to do this.

**Comment by jugglinmike** [comment]
Resolved via gh-119.
