### ISSUE TITLE
add another data point, leave-request-types

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#120]
This will be in support of bocoup/api#293 and https://trello.com/c/sPJhGQgI/37-reporting-by-business-unit. This depends on https://github.com/bocoup/away/issues/298 landing first, as well as an additional release of the API with support on utilizations for associating a leave-request-type.

**Comment by tkellen** [comment]
This is ready for implementation (https://github.com/bocoup/api/pull/295 landed in production this morning).

**Comment by jugglinmike** [comment]
Resolved via gh-123.
