### ISSUE TITLE
Weekly review & admiralty don't match

### ISSUE THREAD

**Issue by iros** [bocoup/nest-weekly-review#137]
On 7/15 @vlandham was away on vacation. This is captured in admiralty:

![image](https://cloud.githubusercontent.com/assets/18690/17104763/56af35d8-5252-11e6-9ddb-1857d381696a.png)

For some reason, the verified utilizations on weekly review are wrong:

![image](https://cloud.githubusercontent.com/assets/18690/17104794/7576a26c-5252-11e6-94a6-25f300424381.png)

Additionally I know I removed one day off consulting for me and changed to initiative lead and that is not captured for my utilizations. Both of these were in place when I verified them last week, so something is off?

Thanks,

**Comment by tkellen** [comment]
This is a display issue, not a data corruption issue. I confirmed with @iros that reloading fixed this.
