### ISSUE TITLE
Ensure utilizations are marked as "verified" when a report is submitted

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/nest-weekly-review#20]

**Comment by jugglinmike** [comment]
@tkellen If I understand the issue correctly, this is already complete. I'm a little confused, though, because the commit that implement it was authored before the issue was filed:

9781c9af8b0b9516aaa203d4892da55507a48734

It might be that I wrote the patch earlier and rebased it... but if you agree this is complete, it might not be worthwhile to ask too many questions.

**Comment by tkellen** [comment]
Confirmed working. There are a few straggler utilizations that are not verified but they are all either new employees (who weren't put in a catch-all phase when they started) or people who left (and got removed from catch-all phases prematurely).
