### ISSUE TITLE
use api authentication and eliminate node server

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#33]
instructions here:
https://github.com/bocoup/api/wiki/Authenticating-Through-The-API

**Comment by tkellen** [comment]
Can we close this @jugglinmike ?

**Comment by jugglinmike** [comment]
This application uses the Nest API for authentication, but it retains a Node server. If you would like to close this, then it would be best to rename the issue first. Then, if eliminating the server is still a priority, we can make a new issue dedicated to that effort.

**Comment by jugglinmike** [comment]
(see https://github.com/bocoup/nest-weekly-review/pull/39 )

**Comment by tkellen** [comment]
this is not a priority, nor needed.
