### ISSUE TITLE
completed reviews green

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#44]
I know we presently have a checkbox for this, but can the reviewed phases be green? I feel like that would be a stronger indication of completeness.

**Comment by jugglinmike** [comment]
Actually, that's just about as ironic as rain on your wedding day. That is to say: it's not ironic at all.

**Comment by jugglinmike** [comment]
Resolved via commit ad9e84f561dc605f3ac26e92271ef0587283a4e2

**Comment by tkellen** [comment]
lol
