### ISSUE TITLE
Extraneous requests sent when dragging utilizations

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/nest-weekly-review#46]
When dragging utilization elements, the application (correctly) sends requests to change the drag target but then (incorrectly) sends additional redundant requests. These extraneous requests fail and trigger error messages in the application UI, making it appear as though the operation was not completed successfully. Although refreshing the current page confirms the intended state of the utilizations concerned, this error should be avoided altogether.

**Comment by jugglinmike** [comment]
@tkellen I tried to resolve this last night, but I could reproduce the bug that I originally experienced. I had worked to fix drag-and-drop previously, and merged 19bb1a889818d85eb13f2f97bde1f2a15c02a3f9 to address that. I would have been happy to mark this bug as "resolved", but I have to imagine there is a problem given that you opened gh-67 just yesterday. Would you mind finding steps to reproduce the bug?

**Comment by tkellen** [comment]
Can do.

**Comment by tkellen** [comment]
I've tried and I can't reproduce this now. If I run across it again I'll get repro steps together!
