### ISSUE TITLE
prevent skipping reviews

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#49]
It should only be possible to review a phase if all weeks behind it have been reviewed. What would the effort look like to make this happen, Mike? As ever, I'm willing to jump in and help if we're running out of your time.

**Comment by jugglinmike** [comment]
Not sure, but I'll try to look into this today

**Comment by jugglinmike** [comment]
@tkellen Would it make sense to implement this as a database constraint?

**Comment by tkellen** [comment]
It wouldn't hurt, but I think it would be pretty bad UX to let someone fill out a review and then be unable to submit it.

**Comment by jugglinmike** [comment]
That wasn't an "either/or" proposition!

**Comment by tkellen** [comment]
Gotcha! Then, yes! It occurs to me now that we might need to prevent changing the start date of a phase if it has a review, as well.

**Comment by tkellen** [comment]
this is not needed.
