### ISSUE TITLE
Application Crashes in Production

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/nest-weekly-review#52]
@tkellen informed me that the deployed application is crashing in response to editing operations.

Tyler & @MattSurabian: could you share a little more detail? Did this occur when setting utilization? If so, was it during a "drag" or when set explicitly with the `<select>` fields? Or did it occur when submitting a review?

**Comment by tkellen** [comment]
It only crashes on submit, the rest of the UI performs flawlessly.

**Comment by jugglinmike** [comment]
This should be resolved in `master` (via 2f1ff279cb8662451ad6696e9d22e86c6adb7aeb), but I want to keep this open until we can confirm in production; that will have to wait until the resolution of gh-55.
