### ISSUE TITLE
Update API request format to latest specification

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/nest-weekly-review#55]
[The API has recently been updated](https://github.com/bocoup/api/pull/164) to more closely match [the JSON API specification](http://jsonapi.org/). This application's request format needs to follow suit.

**Comment by jugglinmike** [comment]
This should be resolved by gh-56

**Comment by tkellen** [comment]
It is.  Thank you Mike!  There will be no future breaking changes that are not opt-in.
