### ISSUE TITLE
Verify Button State

### ISSUE THREAD

**Issue by MattSurabian** [bocoup/nest-weekly-review#57]
The state of the verify buttons doesn't reset when changing weeks from within the verify view.

### To Reproduce

1. Open a project phase on a week that has not been verified, and neither has the next week.
1. Verify the first week, then click "next week" in the top right.

**Expected:** The next week is not verified so the verified buttons should be white.
**Actual:** The verified buttons stay green.

**Comment by jugglinmike** [comment]
@MattSurabian I think this is resolved by gh-65 (specifically 4311091). I've merged and deployed that fix; could you verify?

**Comment by tkellen** [comment]
Confirmed resolved!
