### ISSUE TITLE
saving throws Error: TypeError: undefined is not a function

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#62]
It happens here:
https://github.com/AmpersandJS/ampersand-model/blob/master/ampersand-model.js#L51

Which is called here:
https://github.com/bocoup/nest-weekly-review/blob/master/src/client/modules/models/_base-model.js#L107

I didn't dig any further because I am pretty sure this is something obvious and there is just a gap in my understanding of Ampersand.

**Comment by tkellen** [comment]
![screen shot 2015-02-12 at 8 52 27 am](https://cloud.githubusercontent.com/assets/1004324/6168577/890a5788-b294-11e4-8986-65a116e644b2.png)

**Comment by tkellen** [comment]
Nevermind, I kept digging and I think I've almost solved it.

**Comment by tkellen** [comment]
It's here:
https://github.com/bocoup/nest-weekly-review/blob/master/src/client/modules/models/_base-model.js#L46

**Comment by tkellen** [comment]
This is limited to times when you return to something which has already been reviewed.

**Comment by jugglinmike** [comment]
@tkellen I think this is resolved by gh-65 (specifically 4b046d5). I've merged and deployed; could you verify?

**Comment by tkellen** [comment]
Confirmed resolved!
