### ISSUE TITLE
error when saving

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#64]
Reproduction:

1. click on a utilization
2. hit set (making no changes)
3. click on the same utilization
4. hit set (making no changes)
5. over_utilization error

**Comment by tkellen** [comment]
It seems you are limited to one "set" per employee before saving starts failing.

**Comment by jugglinmike** [comment]
@tkellen I think this is resolved by gh-65 (specifically 1d53a1e). I've merged and deployed; could you verify?

**Comment by tkellen** [comment]
This is resolved!
