### ISSUE TITLE
Disallow modification of previously-verified utilizations

### ISSUE THREAD

**Issue by jugglinmike** [bocoup/nest-weekly-review#66]
@tkellen Is this a feature we want, or am I making this up?

**Comment by tkellen** [comment]
This is a feature we want, yes. The locking behavior happens in Admiralty already.

**Comment by jugglinmike** [comment]
Got it.

**Comment by tkellen** [comment]
However, we might want to hold off on this until the process is in place and working well. I can see myself having to manually un-verify incorrectly entered data a lot in the coming weeks.

**Comment by tkellen** [comment]
this is not a feature we want!
