### ISSUE TITLE
dragging utilizations is broken

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#67]
Reproduction:
1. Go to a reviewed week.
2. Open a reviewed day, set the utilization type to sick, and set.
3. Drag another utilization on top of the sick utilizations.
4. Unique constraint is hit and the change errors out. The UI updates as though it was successful.

**Comment by tkellen** [comment]
Actually, I take that back, it errors but the correct data appears to be persisted.

**Comment by jugglinmike** [comment]
I think this is a duplicate of gh-46. Does that sound right to you?

**Comment by tkellen** [comment]
Seems yes.  Closing!
