### ISSUE TITLE
some utilizations don't have their project selected or incorrect projects are selected

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#68]
I can't find any rhyme of reason to this, but in this particular review:
http://weekly-review.bocoup.com/date/2015-01-04/phase/3/

...Brian shows working on deployer, but when you edit the utilization, the project isn't selected.

**Comment by tkellen** [comment]
Reproduction:
1. set all of brian's utilizations to deployer
2. reload
3. note that the tiles day deployer, but flipping any of them show that deployer is not the selected project.
4. change tuesday to riot client, with or without a phase
5. reload.
4. note that the tiles still show deployer for wed/thur/fri but if you click the tiles, they show riot client selected.

**Comment by jugglinmike** [comment]
Hey Tyler! I think I've resolved this with 5c60b433951968d0377d99ed5d5544d6bd8b02ed . I've deployed that change, so when you get a minute, would you mind confirming?

**Comment by tkellen** [comment]
Confirmed, thank you @jugglinmike !
