### ISSUE TITLE
phase appears incorrectly on tile

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#75]
Reproduction:
1. Go to http://weekly-review.bocoup.com/date/2015-01-04/phase/3/
2. Edit Brian's Tuesday, choosing Riot Client / Phase Three, then hit set.
3. Reload, note that everything is correct.
4. Change Brian's Tuesday to a project without a phase, hit set.
5. Note that Phase 3 is still shown on the tile.
6. Reload.
7. Note that the phase was actually cleared correctly--this is just a UI bug.

**Comment by jugglinmike** [comment]
@tkellen I believe I resolved this issue in 9dd3c7be6744f47599e25df37f362b40f19a79e4 . That change has been deployed (by me!); would you mind confirming the fix?

**Comment by tkellen** [comment]
Confirmed!
