### ISSUE TITLE
dragging utilization when projects differ doesn't update UI

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#79]
Reproduction:
1. Go to http://weekly-review.bocoup.com/date/2015-01-25/phase/3/
2. Change Brian's friday to any other project than his thursday.
3. Hit set.
4. Drag Brian's thursday over friday.
5. Note that the correct API calls are sent, but the UI does not update (reloading shows the correct data was recorded)

**Comment by jugglinmike** [comment]
I just deployed a fix for this from gh-81 . Can you verify?

**Comment by tkellen** [comment]
Confirmed!
