### ISSUE TITLE
changing a utilization doesn't update "verified" button

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#80]
Reproduction:
1. Go to any previously reviewed phase
2. Make any change.
3. Attempt to save.
4. Note that the UI instructs you to verify all employees first.
5. Reload.
6. Note that the verify button is no longer selected for the employee whose utilization was changed.

Note:
It should eventually be the case that any phase week which has been verified cannot be changed, thus preventing this issue entirely, but I feel we should fix this behavior anyway. Eventually, there will likely be some notion of administrative access which allows making correcting entries, or, failing that, an "unlock" button that requires some specific interaction to underscore that making changes is not advisable.

**Comment by jugglinmike** [comment]
@tkellen I've attempted to resolve this via gh-86. Now that that patch is merged and deployed, would you mind verifying? Could you also confirm? And approve?

**Comment by tkellen** [comment]
I can verifiably say that I approve of this adjustment.

**Comment by tkellen** [comment]
Oh shoot, I would also like to confirm that this is working.
