### ISSUE TITLE
project isn't selected when transitioning between phase weeks

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#82]
Reproduction:
1. Go to http://weekly-review.bocoup.com/date/2015-02-08/phase/26/
2. Note that Jenn is on Vacation.
3. Click "Next Week"
4. Note that Jenn is no longer on Vacation, and that her tile shows working on Audience Engine.
5. Click Jenn's Monday.
6. Note that the project is not selected.

**Comment by tkellen** [comment]
@jugglinmike can you confirm if this was the issue with daylight savings time?

**Comment by jugglinmike** [comment]
Resolved via ec2d364150645a71356d52cff111ed4e731145f5
