### ISSUE TITLE
utilizations without projects don't appear flipped?

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#83]
Not 100% sure if the title of this issue accurately represents the underlying problem or not, but here goes:

Reproduction:
1. Visit http://weekly-review.bocoup.com/date/2015-03-08/phase/26/
2. Note that Jenn has Conference time (correctly) selected, but her tile isn't flipped.
3. Trying to set the utilization fails.

![screen shot 2015-03-01 at 2 25 16 pm](https://cloud.githubusercontent.com/assets/1004324/6432413/d49c2c66-c01e-11e4-8f47-2618f4486a6f.png)

![screen shot 2015-03-01 at 2 19 49 pm](https://cloud.githubusercontent.com/assets/1004324/6432398/0c763aa6-c01e-11e4-8c6e-d6abbc9aa0df.png)

**Comment by tkellen** [comment]
Also seeing that if you start here: http://weekly-review.bocoup.com/date/2015-03-01/phase/26/, and hit next week, the utilization type is incorrectly selected as consulting. A reload sets it back to conference.

**Comment by tkellen** [comment]
Confirmed that if you change Jenn's monday utilization to sick and hit next, the utilization type is somehow leaking over, and her monday the next week also show sick.

**Comment by jugglinmike** [comment]
Resolved via gh-87
