### ISSUE TITLE
Jasmin's full staff review view is a week off

### ISSUE THREAD

**Issue by JasminRuth** [bocoup/nest-weekly-review#90]
When  mousingover Jasmin's full staff review the dates appear to be one week behind all other phases in the same column. Clicking on the phase loads the date range listed on mouseover(one week behind). 
For example in the all phases view the column title 3/15 shows the week starting 3/9 for Jasmin's full staff review but for all all other phases it shows week starting 3/16.

Expected is that all phases in the same column are on the same date.

**Comment by jugglinmike** [comment]
@JasminRuth Thanks for the detailed report! I've deployed [a change that I believe fixes the problem](https://github.com/bocoup/nest-weekly-review/commit/f0fb57d8555ff5e4e338405c89aefab14b925065). Would you mind verifying for me?

**Comment by tkellen** [comment]
Just confirmed with @JasminRuth that this was fixed.  Thanks @jugglinmike!
