### ISSUE TITLE
add billable checkbox to utilization panel

### ISSUE THREAD

**Issue by tkellen** [bocoup/nest-weekly-review#97]
This field is present in the API but is currently being ignored. We're ready to use it organizationally, now.

**Comment by tkellen** [comment]
Hey @jugglinmike do you think you'll have any bandwidth to add this before the week is out? This is a critical addition to support the high level reporting we're trying to do about activity happening at Bocoup:
http://bocoup.github.io/nest-dashboard/explore/

**Comment by jugglinmike** [comment]
Yes.

**Comment by tkellen** [comment]
<3 thanks!

**Comment by jugglinmike** [comment]
This feature request is a bit under-specified, but Matt is in the office so I can work with him to find a solution that makes the most sense

**Comment by tkellen** [comment]
I'd be happy to do a call to talk this out any time. Sorry if I wasn't specific enough. A checkbox should appear at the bottom of each utilization panel and be toggle-able to control the value of the `billable` property on each utilization.

**Comment by jugglinmike** [comment]
Thanks, but it will be good for me to get perspective from the users.

For context: I think that the use case warrants that the check box behaves slightly differently than the other form fields. Modifying other fields triggers the creation of a new utilization. For instance: when you have a week-long consulting block and you change Wednesday to "Sick Time", then Monday, Tuesday, Thursday, and Friday remain consulting. I think this new "Billable" field should serve to modify the targeted utilization. For instance: when you have a week-long consulting block and you change Wednesday to "Billable", then the *entire utilization* should become billable.

...I think.

**Comment by tkellen** [comment]
The underlying use-case here is that when someone is sick or on vacation in the middle of a project, we want to track which project they would have been working on. This gives us more visibility around why a given phase hasn't had all of its days delivered. The billable flag allows us to log a day into a phase that isn't billable. As such, I believe it should operate just like the other fields. For example, if you have a non-billable day in the middle of a single week long utilization, you'd wind up with 3 utilizations.

**Comment by tkellen** [comment]
Another use case would be logging consulting work into a phase that isn't billable--for cases when we mess up and need to give away time.

**Comment by tkellen** [comment]
PS: don't take my answers as an admonition to speak with @MattSurabian and @JasminRuth, please do! If you come up with a better solution I'd love to hear it.

**Comment by jugglinmike** [comment]
I talked with Matt, but we need input from Jasmin. I'm going to defer this until she is back from vacation--next Wednesday (May 20) at the earliest.

**Comment by tkellen** [comment]
:+1:

**Comment by tkellen** [comment]
Any updates here?

**Comment by jugglinmike** [comment]
Nope, not yet. I'll keep you posted, though

**Comment by tkellen** [comment]
Okie doke. If there is anything I can do to help, just say the word.

**Comment by MattSurabian** [comment]
Heyo, Jasmin and I have had a chance to talk through this and given the recent changes being implemented in Admiralty it would also be nice to have this billable checkbox in weekly review.
